import json
import subprocess
from pathlib import Path
from .config import settings

def run_ffmpeg(args: list[str]):
    subprocess.run([settings.ffmpeg_bin, "-y", *args], check=True)

def probe(path: str) -> dict:
    result = subprocess.run([settings.ffmpeg_bin, "-i", path, "-hide_banner"], capture_output=True, text=True)
    text = result.stderr
    return {"raw": text}

def replace_audio(video_path: str, voice_path: str, output_path: str):
    run_ffmpeg(["-i", video_path, "-i", voice_path, "-map", "0:v:0", "-map", "1:a:0", "-c:v", "copy", "-c:a", "aac", "-shortest", output_path])
    return output_path

def burn_subtitles(video_path: str, srt_path: str, output_path: str, font_size: int = 48):
    # FFmpeg subtitles filter uses libass. The SRT file is generated by this project.
    escaped = str(Path(srt_path).resolve()).replace("\\", "/").replace(":", "\\:")
    vf = f"subtitles='{escaped}':force_style='FontSize={font_size},Alignment=2,Outline=2,Shadow=1,MarginV=70'"
    run_ffmpeg(["-i", video_path, "-vf", vf, "-c:a", "copy", output_path])
    return output_path

def captions_to_srt(captions, path: str):
    def stamp(ms):
        h, rem = divmod(ms, 3600000); m, rem = divmod(rem, 60000); s, milli = divmod(rem, 1000)
        return f"{h:02d}:{m:02d}:{s:02d},{milli:03d}"
    lines = []
    for i, c in enumerate(captions, 1):
        lines += [str(i), f"{stamp(c.start_ms)} --> {stamp(c.end_ms)}", c.text.strip(), ""]
    Path(path).write_text("\n".join(lines), encoding="utf-8")
    return path
